import type { Config } from "tailwindcss";

export default {
  // darkMode: "selector",
  darkMode: ["variant", ["&:where(.dark, .dark *)", "&:where(:global(.dark), :global(.dark) *)"]], // Fix for dark mode after upgrade to svelte 5
  content: ["./src/**/*.{html,js,svelte,ts}", "./node_modules/flowbite-svelte/**/*.{html,js,svelte,ts}"],
  theme: {
    extend: {
      colors: {
        b: {
          red: "var(--color-b-red)",
          lime: "var(--color-b-lime)",
          yellow: "var(--color-b-yellow)",
          cyan: "var(--color-b-cyan)",
          blue: "var(--color-b-blue)",
          maastricht: "var(--color-b-maastricht)",
          jordy: "var(--color-b-jordy)",
          night: "var(--color-b-night)",
        },
        m: {
          base: "var(--color-m-base)",
          "base-text": "var(--color-m-base-text)",
          "base-subtext0": "var(--color-m-base-subtext0)",
          "base-subtext1": "var(--color-m-base-subtext1)",
          mantle: "var(--color-m-mantle)",
          "mantle-text": "var(--color-m-mantle-text)",
          "mantle-subtext0": "var(--color-m-mantle-subtext0)",
          "mantle-subtext1": "var(--color-m-mantle-subtext1)",
          crust: "var(--color-m-crust)",
          "crust-text": "var(--color-m-crust-text)",
          "crust-subtext0": "var(--color-m-crust-subtext0)",
          "crust-subtext1": "var(--color-m-crust-subtext1)",
          surface0: "var(--color-m-surface0)",
          "surface0-text": "var(--color-m-surface0-text)",
          "surface0-subtext0": "var(--color-m-surface0-subtext0)",
          "surface0-subtext1": "var(--color-m-surface0-subtext1)",
          surface1: "var(--color-m-surface1)",
          "surface1-text": "var(--color-m-surface1-text)",
          "surface1-subtext0": "var(--color-m-surface1-subtext0)",
          "surface1-subtext1": "var(--color-m-surface1-subtext1)",
          surface2: "var(--color-m-surface2)",
          "surface2-text": "var(--color-m-surface2-text)",
          "surface2-subtext0": "var(--color-m-surface2-subtext0)",
          "surface2-subtext1": "var(--color-m-surface2-subtext1)",
          overlay0: "var(--color-m-overlay0)",
          "overlay0-text": "var(--color-m-overlay0-text)",
          "overlay0-subtext0": "var(--color-m-overlay0-subtext0)",
          "overlay0-subtext1": "var(--color-m-overlay0-subtext1)",
          overlay1: "var(--color-m-overlay1)",
          "overlay1-text": "var(--color-m-overlay1-text)",
          "overlay1-subtext0": "var(--color-m-overlay1-subtext0)",
          "overlay1-subtext1": "var(--color-m-overlay1-subtext1)",
          overlay2: "var(--color-m-overlay2)",
          "overlay2-text": "var(--color-m-overlay2-text)",
          "overlay2-subtext0": "var(--color-m-overlay2-subtext0)",
          "overlay2-subtext1": "var(--color-m-overlay2-subtext1)",
          primary: "var(--color-m-primary)",
          "primary-text": "var(--color-m-primary-text)",
          "primary-subtext0": "var(--color-m-primary-subtext0)",
          "primary-subtext1": "var(--color-m-primary-subtext1)",
          secondary: "var(--color-m-secondary)",
          "secondary-text": "var(--color-m-secondary-text)",
          "secondary-subtext0": "var(--color-m-secondary-subtext0)",
          "secondary-subtext1": "var(--color-m-secondary-subtext1)",
          accent: "var(--color-m-accent)",
          "accent-text": "var(--color-m-accent-text)",
          "accent-subtext0": "var(--color-m-accent-subtext0)",
          "accent-subtext1": "var(--color-m-accent-subtext1)",
          neutral: "var(--color-m-neutral)",
          "neutral-text": "var(--color-m-neutral-text)",
          "neutral-subtext0": "var(--color-m-neutral-subtext0)",
          "neutral-subtext1": "var(--color-m-neutral-subtext1)",
          rosewater: "var(--color-m-rosewater)",
          flamingo: "var(--color-m-flamingo)",
          pink: "var(--color-m-pink)",
          mauve: "var(--color-m-mauve)",
          red: "var(--color-m-red)",
          maroon: "var(--color-m-maroon)",
          peach: "var(--color-m-peach)",
          yellow: "var(--color-m-yellow)",
          green: "var(--color-m-green)",
          teal: "var(--color-m-teal)",
          sky: "var(--color-m-sky)",
          sapphire: "var(--color-m-sapphire)",
          blue: "var(--color-m-blue)",
          lavender: "var(--color-m-lavender)",
        },
        primary: {
          50: "#eff6ff",
          100: "#dbeafe",
          200: "#bfdbfe",
          300: "#93c5fd",
          400: "#60a5fa",
          500: "#3b82f6",
          600: "#2563eb",
          700: "#1d4ed8",
          800: "#1e40af",
          900: "#1e3a8a",
          950: "#172554",
        },
      },
    },
  },
  plugins: [
    require("@tailwindcss/typography"),
    require("flowbite-typography"),
    require("@catppuccin/tailwindcss")({
      prefix: "ctp",
      defaultFlavour: "mocha",
    }),
  ],
} satisfies Config;
